# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  currency-app:
    # Configuration for building the docker image for the backend service
    build:
      context: ./ # Use an image built from the specified dockerfile in the `parent` directory.
      dockerfile: Dockerfile #When you define a context in docker-compose, the dockerfile: bit is relative to that context.
    ports:
      - "8081:9091" # Forward the exposed port 9091 on the container to port 8081 on the host machine
    restart: always
    depends_on:
      - mysql # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      #SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      #SPRING_DATASOURCE_USERNAME: callicoder
      #SPRING_DATASOURCE_PASSWORD: callicoder
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - mynetwork

  # Database Service (Mysql)
  mysql:
    image: mysql:8.0.17
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currency_conversion_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynetwork

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  mynetwork: