# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

#Use docker inspect <containerid> to get the mysql ip.
#we can also provide the spring configuration check - https://docs.spring.io/spring-boot/docs/2.1.11.RELEASE/reference/html/boot-features-external-config.html
ENV MYSQL_HOST=docker_practice_mysql-development_1
ENV MYSQL_PORT=3306
ENV MYSQL_USERNAME=root
ENV MYSQL_PASSWORD=root

# Add Maintainer Info
LABEL maintainer="rahulsharma.bbiet@gmail.com"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 9091

# The application's jar file
ARG JAR_FILE=target/currency-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} currency.jar

# Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","currency.jar"]
